id: AAF66A6CB
title: 'The Offering Clouds of the Indestructible Ladies of Sound: Concise Garland
  of Offerings of the Sixteen Vajra Goddesses'
type: translation
pechas:
- IAD32EAE9
- I0ECF1833
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:35:04.981908
  last_modified_at: 2023-01-04 12:35:04.981913
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IAD32EAE9/06F4: 652D
  I0ECF1833/208B: 652D
